routes/web.php
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('general', 'DashboardController@general');
        Route::get('sales', 'DashboardController@sales');
        Route::get('general', 'DashboardController@general');
    });

    //Slide
    Route::group(['prefix' => 'slides'], function () {
        Route::get('edit/{id}', 'SlideController@edit')->name('slides.edit_slide');
        Route::post('edit/{id}', 'SlideController@update');
        Route::post('upload-image/{id?}', 'SlideController@uploadImage')->name('slides.upload');
        Route::post('edit-image/{id?}', 'SlideController@editImage')->name('slides.edit');
        Route::delete('delete-image/{id?}', 'SlideController@deleteImage')->name('slides.delete');
        Route::get('get-image/{id?}', 'SlideController@getImage')->name('slides.get');
        Route::post('order', 'SlideController@orderImages')->name('slides.order');
    });

    //Gallery
    Route::group(['prefix' => 'galleries'], function () {
        Route::post('upload-image/{id?}', 'GalleryController@uploadImage')->name('galleries.upload');
        Route::post('edit-image', 'GalleryController@editImage')->name('galleries.edit');
        Route::delete('delete-image/{id?}', 'GalleryController@deleteImage')->name('galleries.delete');
        Route::get('get-image/{id?}', 'GalleryController@getImage')->name('galleries.get');
        Route::post('order', 'GalleryController@orderImages')->name('galleries.order');
    });

    //Files
    Route::group(['prefix' => 'files'], function () {
        Route::post('upload-file/{id?}', 'FileController@uploadFile')->name('files.upload');
        Route::post('edit-file', 'FileController@editFile')->name('files.edit');
        Route::delete('delete-file/{id?}', 'FileController@deleteFile')->name('files.delete');
        Route::get('get-file/{id?}', 'FileController@getFile')->name('files.get');
        Route::post('order', 'FileController@orderFiles')->name('files.order');
    });

    //Video
    Route::group(['prefix' => 'videos'], function () {
        Route::any('upload-video/{id?}', 'VideoController@upload')->name('videos.upload');
        Route::post('edit-video', 'VideoController@edit')->name('videos.edit');
        Route::delete('delete-video/{id?}', 'VideoController@delete')->name('videos.delete');
        Route::get('get-video/{id?}', 'VideoController@get')->name('videos.get');
        Route::post('order', 'VideoController@order')->name('videos.order');
    });

    //Category
    Route::group(['prefix' => 'categories'], function () {
        Route::get('get/{id?}', 'CategoryController@get')->name('categories.get');
        Route::post('edit/{id?}', 'CategoryController@edit')->name('categories.edit');
        Route::get('list/{id?}/{type?}', 'CategoryController@index')->name('categories.list');
        Route::delete('delete/{id?}', 'CategoryController@delete')->name('categories.delete');
        Route::post('order', 'CategoryController@order')->name('categories.order');
        Route::post('upload-image', 'CategoryController@uploadImage')->name('categories.upload_image');
    });

    //Contents
    Route::group(['prefix' => 'contents'], function () {
        Route::get('list', 'ContentController@index')->name('contents.list');
        Route::get('json-list', 'ContentController@jsonList');
        Route::get('edit/{id}', 'ContentController@edit')->name('contents.edit');
        Route::post('edit/{id}', 'ContentController@updateOrCreate');
        Route::get('categories', 'ContentController@categories')->name('contents.categories');
        Route::delete('delete/{id}', 'ContentController@delete');
    });

    //Articles
    Route::group(['prefix' => 'articles'], function () {
        Route::get('list', 'ArticleController@index')->name('articles.list');
        Route::get('json-list', 'ArticleController@jsonList');
        Route::get('edit/{id}', 'ArticleController@edit')->name('articles.edit');
        Route::post('edit/{id}', 'ArticleController@updateOrCreate');
        Route::get('categories', 'ArticleController@categories')->name('articles.categories');
        Route::delete('delete/{id}', 'ArticleController@delete');
    });

    //Services
    Route::group(['prefix' => 'services'], function () {
        Route::get('list', 'ServiceController@index')->name('services.list');
        Route::get('json-list', 'ServiceController@jsonList');
        Route::get('edit/{id}', 'ServiceController@edit')->name('services.edit');
        Route::post('edit/{id}', 'ServiceController@updateOrCreate');
        Route::get('categories', 'ServiceController@categories')->name('services.categories');
        Route::delete('delete/{id}', 'ServiceController@delete');
        Route::post('order', 'ServiceController@order')->name('services.order');
        Route::get('get-all', 'ServiceController@get')->name('services.get_all');
    });

    //Locations
    Route::group(['prefix' => 'locations'], function () {
        Route::get('list', 'LocationController@index')->name('locations.list');
        Route::get('json-list', 'LocationController@jsonList');
        Route::get('edit/{id}', 'LocationController@edit')->name('locations.edit');
        Route::post('edit/{id}', 'LocationController@updateOrCreate');
        Route::delete('delete/{id}', 'LocationController@delete');
    });

    //Subscribes
    Route::group(['prefix' => 'subscribers'], function () {
        Route::get('list', 'SubscriberController@index')->name('subscribers.list');
        Route::get('json-list', 'SubscriberController@jsonList');
        Route::delete('delete/{id}', 'SubscriberController@delete');
        Route::get('export', 'SubscriberController@export')->name('subscribers.export');
    });

    //Configsite
    Route::group(['prefix' => 'configsite'], function () {
        Route::get('edit', 'ConfigsiteController@edit')->name('configsite.edit');
        Route::post('edit', 'ConfigsiteController@update');
    });

    //Account
    Route::group(['prefix' => 'account'], function () {
        Route::get('edit', 'AccountController@edit')->name('account.edit');
        Route::post('edit', 'AccountController@update');
    });

    //Users

    Route::group(['prefix' => 'users'], function () {
        Route::get('list', 'UserController@index')->name('users.list');
        Route::get('json-list', 'UserController@jsonList');
        Route::get('edit/{id}', 'UserController@edit')->name('users.edit');
        Route::post('edit/{id}', 'UserController@updateOrCreate');
        Route::post('delete/{id}', 'UserController@delete');
    });


    Route::group(['prefix' => 'lottery'], function () {
        Route::get('list', 'LotteryController@index')->name('lottery.list');
        Route::get('json-list', 'LotteryController@jsonList');
        Route::get('edit/{id}', 'LotteryController@edit')->name('lottery.edit');
        Route::post('edit/{id}', 'LotteryController@updateOrCreate');
        Route::post('delete/{id}', 'LotteryController@delete');

        Route::post('block-number', 'LotteryController@saveblock')->name('lottery.save_block');
        Route::get('delete-block-number/{id?}', 'LotteryController@deleteblock')->name('loterry.delete_number');
    });


    Route::group(['prefix' => 'bet'], function () {
        Route::get('list', 'BetController@index')->name('bet.list');
        Route::get('json-list', 'BetController@jsonList');
        Route::get('edit/{id}', 'BetController@edit')->name('bet.edit');
        Route::post('edit/{id}', 'BetController@updateOrCreate');
        Route::post('delete/{id}', 'BetController@delete');
        Route::get('export', 'BetController@export')->name('bet.export');

        Route::get('preview/{id}', 'BetController@preview')->name('bet.preview');

        Route::post('update_printed','BetController@updatePrint')->name('update_printed');
        Route::get('print/{id}', 'BetController@printPdf')->name('bet.print');


        Route::post('validate', 'BetController@validateNumber')->name('validate_number');
        Route::post('get-lottery', 'BetController@getLottery')->name('get_loterry');
    });


    Route::group(['prefix' => 'sellers'], function () {
        Route::get('list', 'SellerController@index')->name('sellers.list');
        Route::get('json-list', 'SellerController@jsonList');
        Route::get('edit/{id}', 'SellerController@edit')->name('sellers.edit');
        Route::post('edit/{id}', 'SellerController@updateOrCreate');
        Route::delete('delete/{id}', 'SellerController@delete');
        Route::get('get-seller/{id?}','SellerController@getSeller')->name('sellers.getName');
        Route::post('delete-seller','SellerController@deleteSeller')->name('sellers.deleteSeller');
    });

    Route::group(['prefix' => 'reports'], function () {
        Route::get('sellers', 'ReportController@sellers')->name('reports.sellers');

    });

    Route::group(['prefix' => 'draws'], function () {
        Route::get('list', 'DrawController@index')->name('draws.list');
        Route::get('json-list', 'DrawController@jsonList');
        Route::post('edit/{id}', 'DrawController@updateOrCreate')->name('draws.update');
        Route::delete('delete/{id}', 'DrawController@delete');

        //Winners
        Route::get('winners/list/{id}', 'DrawController@indexWinners')->name('draws.winners');
        Route::get('winners/json-list/{id}', 'DrawController@jsonListWinners')->name('draws.json_winners');
        Route::delete('winners/delete/{id?}', 'DrawController@deleteWinner')->name('draws.delete_winner');
        Route::get('winners/export/{id}', 'DrawController@exportWinners')->name('draws.winners.export');
    });

    Route::group(['prefix' => 'payments'], function () {
        Route::get('pay', 'PaymentController@payment')->name('payment.pay');
    });


    Route::group(['prefix' => 'reports'], function () {
        Route::get('ventas', 'ReportsController@sales')->name('reports.sale');

app/Models/Bet.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Bet extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    /**
     * Números de la chancha.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     * Created by <Rhiss.net>
     */
    public function numbers()
    {
        return $this->hasMany(BetNumber::class);
    }

    /**
     * @return string
     * Created by <Rhiss.net>
     */
    public function getCodeAttribute()
    {
         return $this->seller_code . ' '. format_consecutive($this->consecutive, 4);
    }


}

resources/views/exports/pdf/bet.blade.php
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

        <style type="text/css">
    
            @page { header: page-header ; margin-top:90px; margin-left:10px;margin-right:10px;margin-bottom:1px; }

            body {
                font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
                -webkit-font-smoothing: antialiased;
                color: rgba(0, 0, 0, 0.87);
                background-color: transparent;
                
            }

            .panel .table {
                border-color: #e7e8ea !important;
                }

                .table > tbody > tr > td,
                .table > tfoot > tr > td,
                .table > tbody > tr > th,
                .table > tfoot > tr > th {
                padding: 12px 24px;
                border-top: 1px solid #e7e8ea;
                }

                .table > thead > tr > th {
                padding: 12px 24px;
                border-bottom: 1px solid #e7e8ea;
                }

                .table-bordered {
                border-color: #e7e8ea;
                }

                .table-bordered > tbody > tr > td,
                .table-bordered > tbody > tr > th {
                border-color: #e7e8ea;
                }

                .table-bordered > thead > tr > th {
                border-color: #e7e8ea;
                }

                .table-striped > tbody > tr:nth-child(odd) > td,
                .table-striped > tbody > tr:nth-child(odd) > th {
                background-color: #f6f6f7;
                }

                .table-striped > thead > th {
                background-color: #f6f6f7;
                border-right: 1px solid #e7e8ea;
                }

                .table-striped > thead > th:last-child {
                border-right: none;
                }

                [md-ink-ripple] {
                position: relative;
                }
    
            tfoot tr td {
                font-weight : bold;
                font-size   : x-small;
            }
    
            .gray {
                background-color : lightgray
            }
    
         
            #revise {
                position : fixed;
                top      : 3%;
                left     : 28%;
                opacity  : .4;
            }
    
            .text-italic {
                font-style : italic;
            }
            
            .text-right{
                text-align: right;
            }
           
            .font-size{
                font-size: 12px;
            }

            .font-size-2{
                font-size: 10px;
            }


            .font-size-3{
                font-size: 8px;
            }

            .font-size-4{
                font-size: 10px;
            }
    
            .text-center {
                text-align: center;
            }
            .p-5 {
                padding : 10px 5px;
            }
            .page_break { page-break-before: always; }
        </style>
    
</head>
<body >
<htmlpageheader name="page-header" class="text-center " width="100%">
    <table class="table table-striped table-bordered"  width="100%" style="display:block">
        <tbody>
            <tr>
                <td colspan="2" class="text-center font-size">APUESTAS INKASOL S.A.C<br/><span class="font-size-3">RUC 20604661049</span></td>
            </tr>
            <tr>
                <td  class="font-size-3"> # {{$bet->code}}</td>
                <td class="font-size-3" > {{format_date($bet->date)}}</td>
            </tr>
            <tr>
                <td colspan="2" class="text-left font-size-3" >Chancha: {{  App\Http\Controllers\BetController::getchancha($bet->loterry_id) }}</td>  
            </tr>
        </tbody>
    </table>
</htmlpageheader>
<htmlpagefooter ></htmlpagefooter>
<main id='test'>
    @php 
    
    $total = count($numbers) ; $pages = ceil($total / 4); $n=1;$block[$n] = '';$k=0; $partial[$n]=0; 

    foreach($numbers as $number){

            $k++;
            $length = strlen($number->number);

            $astrics = 4 - $length;

            $final_number = $number->number;
            for($i=1; $i<($astrics +1); $i++){
                $final_number = '*'.$final_number;
            }
            
            
            $block[$n].='<tr>
                <td class="text-center font-size-4" width="20%">'.$final_number.'</td>
                <td class="text-center font-size-4" width="20%"> '. (($length > 2 && $number->combinated == 0)? price_format($number->amount) :'*') .'</td>
                <td class="text-center font-size-4" width="20%"> '. (($length > 2 && $number->combinated == 1)? price_format($number->amount) :'*')  .'</td>
                <td class="text-center font-size-4" width="20%"> '. (($length == 2)? price_format($number->amount) :'*') .'</td>
                <td class="text-center font-size-4" width="20%">'. (($length == 1)? price_format($number->amount) :'*') .'</td>
            </tr>';

            $partial[$n] += $number->amount;

            if( $k%4==0){
                $n++;
                $block[$n] = '';
                $partial[$n] = 0;
            }
            

         }

    @endphp

    @for($i=1; $i<$pages+1;$i++)
        @php $z = $i; @endphp
  
    <table class="table table-striped table-bordered" width="100%">   
        <tbody>
           
            <tr>
                <td colspan="5" class="font-size-3">&nbsp;</td>
            </tr>
            <tr>
                <td class="text-center font-size-3" ><strong>Num </strong></td>
                <td class="text-center font-size-3" ><strong>Dir</strong></td>
                <td class="text-center font-size-3" ><strong>Com</strong></td>
                <td class="text-center font-size-3" ><strong>Dos</strong></td>
                <td class="text-center font-size-3" ><strong>Un</strong></td>
            </tr>
            {!! $block[$z] !!}
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3" width="80%" class="text-right font-size"><strong>Total:</strong></td>
                <td colspan="2"  class="text-right font-size-4">{{price_format($partial[$z])}}</td>
            </tr>
            </tbody>
        </table>

        @if($i<$pages)
        <div class="page_break"></div>
        @endif
    @endfor
</main>


<script src="{{ asset('js/admin-global.min.js') }}" defer></script>
<a class="btn btn-sm btn-outline-main" onclick="printJS({printable: \'bet_form\', type: \'html\', header: \'PrintJS - Form Element Selection\'})">
                                        
    <i class="fa fa-print"></i> Imprimir</a>
</body>

</html>